
# Manual provisioning configuration
provisioning:
  source: "manual"
  device_connection_string: "HostName=NuvlaBox-Test.azure-devices.net;DeviceId=cmd-test;SharedAccessKey=kmlzt9PwY9RKCbNgHsUS7e9/VUQ/cpue17KnltyKLiU="
agent:
  name: "edgeAgent"
  type: "docker"
  env: {}
  config:
    image: "mcr.microsoft.com/azureiotedge-agent:1.0"
    auth: {}
hostname: "8c7fe9bb72d3"
connect:
  management_uri: "unix:///var/run/iotedge/mgmt.sock"
  workload_uri: "unix:///var/run/iotedge/workload.sock"
listen:
  management_uri: "fd://iotedge.mgmt.socket"
  workload_uri: "fd://iotedge.socket"
homedir: "/var/lib/iotedge"
moby_runtime:
  uri: "unix:///docker/docker.sock"
