version: '3.6'

services:
  azure-iot-edge:
    image: 'azure_runtime'
    container_name: 'azure-iot-edge'
    network_mode: 'host'
    privileged: true
    volumes: 
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    configs:
      - source:  service_file
        target: '/opt/azure/'

configs:
  service_file: 
    file: './entrypointEnvs'  